# Generated by Django 3.2.4 on 2021-07-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('prep_time', models.DurationField(verbose_name='Enter here')),
                ('cooking_time', models.DurationField(verbose_name='Enter here')),
                ('servings', models.IntegerField()),
            ],
        ),
    ]
