# Generated by Django 3.2.4 on 2021-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210701_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecard',
            name='cooking_time',
            field=models.DurationField(verbose_name='HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='recipecard',
            name='prep_time',
            field=models.DurationField(verbose_name='HH:MM:SS'),
        ),
    ]
