# Generated by Django 3.2.4 on 2021-07-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210701_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecard',
            name='cooking_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='recipecard',
            name='prep_time',
            field=models.DurationField(),
        ),
    ]
