# Generated by Django 3.2.4 on 2021-08-25 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_alter_methodstep_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipecard',
            name='recipe_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipecard',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
