# Generated by Django 3.2.4 on 2021-09-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210825_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecard',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='recipecard',
            name='prep_time',
        ),
        migrations.AddField(
            model_name='recipecard',
            name='active_time_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipecard',
            name='active_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipecard',
            name='total_time_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipecard',
            name='total_time_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
