# Generated by Django 3.2.4 on 2021-09-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210914_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecard',
            name='recipe_description',
            field=models.TextField(default='Generic description', max_length=200),
            preserve_default=False,
        ),
    ]
