# Generated by Django 3.2.4 on 2021-09-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecard',
            name='active_time_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipecard',
            name='active_time_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipecard',
            name='total_time_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipecard',
            name='total_time_minutes',
            field=models.IntegerField(),
        ),
    ]
